@baseurl = http://localhost:5092/api

### Create Product
POST {{baseurl}}/product/Create
Content-Type: application/json
{
  "title": "Gaming Laptop",
  "description": "High performance laptop",
  "price": 1500,
  "brandId": "00000000-0000-0000-0000-000000000000"
}


Get {{baseurl}}/product/getProduct
Content-Type: applicatoin/json
{
  "title": "Gaming Laptop"
}

### Create brand 
POST {{baseurl}}/brand/create
Content-Type: application/json
{
  "name": "Puma",
}

### Get brand
GET {{baseurl}}/brand/getBrand
Content-Type : application/json
{
  "name": "Puma"
}