@ECommerce.Presentation.Web.Api_HostAddress = http://localhost:5092

### Create Product
POST {{ECommerce.Presentation.Web.Api_HostAddress}}/api/product/Create
Content-Type: application/json
{
  "title": "Gaming Laptop",
  "description": "High performance laptop",
  "price": 1500,
  "brandId": "00000000-0000-0000-0000-000000000000"
}